const express = require('express')
const Router = express.Router()


const { getState }	    = require('./getState')
const { getAuth }		    = require('./getAuth')
const { getWorkshop }		= require('./getWorkshop')
const { getOffice }			= require('./getOffice')
const { getPass }			  = require('./getPass')
const { getSoftware }		= require('./getSoftware')
const { getConnect }		= require('./getConnect')
const { getCleaning }		= require('./getCleaning')
const { getNIP }			  = require('./getNIP')
const { getVIN }			  = require('./getVIN')
const { getCookies }		= require('./getCookies')
const { uploadFile }		= require('./uploadFile')
const { deleteFile }		= require('./deleteFile')
const { deleteFolder }	= require('./deleteFolder')

Router.post('/getState', 	    (req, res)=> getState(req, res)     )
Router.post('/getAuth',       (req, res)=> getAuth(req, res)      )
Router.post('/getWorkshop',   (req, res)=> getWorkshop(req, res) 	)
Router.post('/getOffice', 	  (req, res)=> getOffice(req, res) 	  )
Router.post('/getPass', 	    (req, res)=> getPass(req, res) 	    )
Router.post('/getSoftware', 	(req, res)=> getSoftware(req, res) 	)
Router.post('/getConnect', 	  (req, res)=> getConnect(req, res) 	)
Router.post('/getCleaning', 	(req, res)=> getCleaning(req, res) 	)
Router.post('/getNIP',        (req, res)=> getNIP(req, res)       )
Router.post('/getVIN',        (req, res)=> getVIN(req, res)       )
Router.post('/getCookies',    (req, res)=> getCookies(req, res)   )
Router.post('/uploadFile', 	  (req, res)=> uploadFile(req, res) 	)
Router.post('/deleteFile', 	  (req, res)=> deleteFile(req, res) 	)
Router.post('/deleteFolder', 	(req, res)=> deleteFolder(req, res) )

module.exports = Router